### ISSUE TITLE
Secrets notation YAML support

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/tracehub#162]
as described [here](https://github.com/tracehubpm/tracehub?tab=readme-ov-file#secret-variables), we should support a YAML secrets notation, consider this example:
```yaml
id: 5B0185CB-424B-42D4-9631-7B628B7BB78F
...
key: ${value}
```
In this case, when reading the `${value}`, we should fetch the secret called `value` inside project with id `5B0185CB-424B-42D4-9631-7B628B7BB78F` and use it further
