### ISSUE TITLE
Turn it into GitHub action

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/tracehub#169]
Let's turn this Tracehub application into a configurable GitHub action. First of all, it will be more stable (hosted service can experience downtimes and so on) and there is no need to host it, and users can use the whole tracehub functionality in packaged GitHub action, for instance `tracehub.yml`:

```yml
name: tracehub
on:
  # we need to define all process we handling, according to current tracehub functionality and event handlers
  ...
permissions:
  # write permissions for all entities that we interact with
   ...
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        # pack it using docker
      - uses: docker://tracehub/tracehub:latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # probably we will need to define more inputs
```
